### ISSUE TITLE
update to 2.2

### ISSUE THREAD

**Issue by andreas-h** [conda-forge/paramiko-feedstock#13]
Hi, it would be great to update this to Paramiko 2.2.

I have a project requiring 2.2 (due to ed25519 host keys), and it would be great to see paramiko 2.2 in conda-forge :-)

**Comment by pmlandwehr** [comment]
There's a [version in the works](https://github.com/conda-forge/paramiko-feedstock/), but it's been held up due to issues with getting `pynacl` to build correctly on windows.

**Comment by jakirkham** [comment]
Updated to 2.2.1 in PR ( https://github.com/conda-forge/paramiko-feedstock/pull/10 ) and subsequently updated to even more recent versions since. Closing as resolved.
